[package]
name = "cashweb-keyserver"
version = "0.1.0-alpha.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
prost = "0.6.1"

[build-dependencies]
prost-build = "0.6.1"
