dist: bionic
language: rust
rust:
  - stable

cache: cargo
before_install:
  - sudo apt update
  - sudo apt install -y pkg-config libzmq3-dev libssl-dev

jobs:
  include:
  - stage: build
    script:
      cargo build --verbose
  - stage: unittest
    script:
    - cargo test bitcoin
    - cargo test crypto
  - stage: regtest
    script:
    - sudo add-apt-repository -y ppa:bitcoin-abc/ppa
    - sudo apt-get update
    - sudo apt install -y libzmq3-dev
    - sudo apt install -y bitcoind
    - bitcoind -daemon -regtest -zmqpubrawtx=tcp://127.0.0.1:28332 -rpcallowip=0.0.0.0/0 -server -rpcuser=username -rpcpassword=password -rpcport=18332
    - sleep 15
    - bitcoin-cli -regtest -rpcuser=username -rpcpassword=password generate 101
    - NEW_ADDRESS=$(bitcoin-cli -regtest -rpcuser=username -rpcpassword=password getnewaddress)
    - bitcoin-cli -regtest -rpcuser=username -rpcpassword=password -regtest sendtoaddress $NEW_ADDRESS 20.00
    - cargo test
  