[package]
name = "keyserver"
version = "0.1.0"
authors = ["harry <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "*"
actix-web = "*"
actix-service = "*"
actix-rt = "*"
base64 = "*"
bitcoin = "*"
bitcoin-zmq = { git = "https://github.com/hlb8122/rust-bitcoin-zmq.git" }
bitcoin_hashes = "*"
bytes = "*"
clap = { version = "*", features = ["yaml"] }
config = "*"
dirs = "*"
env_logger = "*"
hex = "*"
lazy_static = "*"
log = "*"
futures = "*"
prost = "*"
reqwest = "*"
rocksdb = "*"
secp256k1 = "0.12.0"
serde = "*"
serde_json = "*"
serde_derive = "*"
rust-base58 = "*"
url = "*"

[build-dependencies]
prost-build = "*"

[dev-dependencies]
secp256k1 = { version = "*", features = ["rand"] }
bigdecimal = { version = "*", features = ["serde"] }
