[package]
name = "keyserver"
version = "0.1.0"
authors = ["harry <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "*"
prost = "*"
rocksdb = "*"
bytes = "*"
secp256k1 = "*"
bitcoin_hashes = "*"
serde = "*"
serde_json = "*"
reqwest = "*"
actix-web = "*"
hex = "*"
env_logger = "*"
actix-files = "*"

[build-dependencies]
prost-build = "*"
