[package]
name = "keyserver"
version = "0.1.0"
authors = ["harry <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "*"
actix-web = "*"
actix-service = "*"
bitcoin_hashes = "*"
bytes = "*"
env_logger = "*"
prost = "*"
reqwest = "*"
secp256k1 = "*"
rocksdb = "*"
serde = "*"
serde_json = "*"
futures = "*"
rust-base58 = "*"

[build-dependencies]
prost-build = "*"

[dev-dependencies]
hex = "*"
