[package]
name = "pop-middleware"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1.20"
prost = "0.5.0"
bytes = "0.4.7"
async-trait = "0.1.19"
futures = "0.3.1"

[build-dependencies]
prost-build = "0.5.0"
