[package]
name = "tower-pop"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
http = "0.1"
hyper = "0.12"
prost = "0.5"
bytes = "0.4"
futures = { version = "0.3", features = ["compat"] }
tower-service = "0.3"
tower-layer = "0.3"

[build-dependencies]
prost-build = "0.5.0"
