[package]
name = "keyserver"
version = "0.1.0"
authors = ["harry <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "*"
prost = "*"
rocksdb = "*"
bytes = "*"

[build-dependencies]
prost-build = "*"
