[package]
name = "cashweb-broadcast"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
async-json-rpc = { git = "https://github.com/hlb8122/async-json-rpc" }
hyper = "0.13.0"
tower-service = "0.3.0"
