[package]
name = "cashweb"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
payments = { package = "cashweb-payments", path = "../cashweb-payments" }
protobuf = { package = "cashweb-protobuf", path = "../cashweb-protobuf" }
protection = { package = "cashweb-protection", path = "../cashweb-protection" }
token = { package = "cashweb-token", path = "../cashweb-token" }
