[package]
name = "cashweb-keyserver-client"
version = "0.1.0-alpha.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.5"
futures-core = "0.3.5"
futures-util = "0.3.5"
hyper = { version = "0.13.6", features = ["stream"] }
hyper-tls = "0.4.3"
rand = "0.7.3"
tokio = { version = "0.2.21", features = ["sync"] }
tower-service = "0.3.0"
tower-util = "0.3.1"
prost = "0.6.1"

auth-wrapper = { version = "0.1.0-alpha.0", package = "cashweb-auth-wrapper", path = "../cashweb-auth-wrapper" }
keyserver = { version = "0.1.0-alpha.0", package = "cashweb-keyserver", path = "../cashweb-keyserver" }
secp256k1 = { package = "cashweb-secp256k1", version = "0.17.3" }
