[package]
name = "cashweb-keyserver-client"
version = "0.1.0-alpha.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.36"
futures-core = "0.3.5"
hyper = { version = "0.13.6", features = ["stream"] }
tower-service = "0.3.0"
tower-util = "0.3.1"
prost = "0.6.1"

auth-wrapper = { version = "0.1.0-alpha.0", package = "cashweb-auth-wrapper", path = "../cashweb-auth-wrapper" }

[build-dependencies]
prost-build = "0.6.1"
