dist: bionic
language: rust
rust:
  - stable

cache: cargo
before_install:
  - sudo apt update

jobs:
  include:
  - stage: build
    script:
      cargo build --verbose
  - stage: unittest
    script:
    - cargo test
