[package]
name = "cashweb-bitcoin"
version = "0.1.0-alpha.1"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.5"
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1", rev = "a5147bbf015ca61bb0e4e09adb8e9b324965c291" }
ring = "0.16.15"
serde = { version = "1.0.114", features = ["derive"] }

[dev-dependencies]
hex = "0.4.2"
criterion = "0.3"

[[bench]]
name = "transaction"
harness = false