[package]
name = "cashweb-bitcoin-client"
version = "0.1.0-alpha.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/cashweb/cashweb-rs"
repository = "https://github.com/cashweb/cashweb-rs"
keywords = ["cashweb", "bitcoin", "client"]
description = "A minimal Bitcoin RPC client."
categories = ["development-tools"]

[dependencies]
hex = "0.4.2"
json-rpc = { package = "async-json-rpc", version = "0.1.0" }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
