[package]
name = "cashweb-protection"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
http = "0.2.0"

token = { package = "cashweb-token", path = "../cashweb-token" }
