[package]
name = "cashweb-protobuf"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
prost = { git = "https://github.com/danburkert/prost" }
bytes = "0.5.3"

[build-dependencies]
prost-build = { git = "https://github.com/danburkert/prost" }
