[package]
name = "cashweb-protobuf"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
prost = "0.6.1"
bytes = "0.5.4"

[build-dependencies]
prost-build = "0.6.1"
