[package]
name = "cashweb-token"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
bitcoin = "0.23.0"
bitcoin-client = { package = "cashweb-bitcoin-client", path = "../cashweb-bitcoin-client" }
base64 = "0.12.0"
http = "0.2.1"
ring = "0.16.12"
