[package]
name = "cashweb-token"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
futures-core = "0.3.1"
futures-util = "0.3.1"
http = "0.2"
ring = "0.16.9"
tower-service = "0.3.0"
tower-layer = "0.3.0"

protobuf = { package = "cashweb-protobuf", path = "../cashweb-protobuf" }
